### ISSUE TITLE
NV -> KHR ray tracing extensions migration for Vulkan

### ISSUE THREAD

**Issue by BattleAxeVR** [NVIDIA-RTX/NRD#13]
Just wondering if this is on the roadmap (one would presume). I guess it doesn't matter if I'm just using the base NRD integration instead of NRI wrapper, but I wonder if this is coming soon.

Thanks.

**Comment by dzhdanNV** [comment]
Your vision is incorrect:
APP (NRD consumer) => NRDIntegration layer (NRI based) OR integration using engine capabilities => NRD

`NRD` - no RT. That's it
`NRDIntegration layer` - no RT, doesn't require RT extension from NRI, uses NRI to wrap native GAPI pointers into NRI entities (textures, command buffer...)
`APP (NRD sample in my case)` - uses NRI to be API agnostic. RT in VULKAN is implemented using NV extension

Finally, the answer to your question:
- yes, we would like to move to KHR RT ASAP
- in the future I would like to try out `TraceRayInline` in my tracer

**Comment by ch45er** [comment]
_Nb: this seemed to be a proper place to post, but can move to a different thread if required._

The DXC command line for Vulkan (in CompileShaders.bat) looks inconsistent with the sample code.
Specifically, it sets just the `-fspv-target-env=vulkan1.2` flag. According to DXC [wiki ](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#raytracing-shader-stages) this implies use of `SPV_KHR_ray_tracing ` extension.

When compiling shaders with this command line I get the following validation error at runtime:
```
[nri(VULKAN)::ERROR] -- DebugUtilsMessenger: error, 7060244 UNASSIGNED-CoreValidation-Shader-InconsistentSpirv Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x27262bfa438, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Operand 1 of EntryPoint requires one of these capabilities: RayTracingKHR RayTracingNV 
  OpEntryPoint RayGenerationNV %Raytracing00_rgen "Raytracing00_rgen" %globalConstants %gLinearMipmapLinearSampler %gNearestMipmapNearestSampler %gLinearSampler %gWorldTlas %gLightTlas %gIn_PrimitiveData %gIn_InstanceData %gIn_Textures %gIn_Scrambling_Ranking_1spp %gIn_Scrambling_Ranking_32spp %gIn_Sobol %gIn_IntegratedBRDF %gIn_PrevColor_PrevViewZ %gOut_DirectLighting %gOut_TransparentLighting %gOut_ObjectMotion %gOut_ViewZ %gOut_Normal_Roughness %gOut_BaseColor_Metalness %gOut_ShadowData %gOut_Diff %gOut_Spec %gOut_Shadow_Translucency %27 %payload
```
I presume this is because the sample uses NV extension. To fix that I had to add `-fspv-extension=SPV_NV_ray_tracing -fspv-extension=SPV_EXT_descriptor_indexing` to the command line.

Am I misusing the sample code or its dependencies or this is a bug? I am on v.2.1.0.
