### ISSUE TITLE
Reblur Compatibility with DLSS 2.1

### ISSUE THREAD

**Issue by BattleAxeVR** [NVIDIA-RTX/NRD#14]
Hi, with NVidia shipping DLSS to all Unreal developers now, I'm curious how that fits in with NRD / Reblur and this repo. 

Can we use both at the same time? Are there plans for further / tighter integration here?

It's not clear to my mind after reading news reports on it how DLSS on its own deals with noisy images in Raytracing scenes. I assume those scenes must be using a denoiser of some kind but I'm curious if DLSS on its own does denoising as part of the upscaling process. 

Thanks.

**Comment by dzhdanNV** [comment]
DLSS != denoiser. But DLSS = noise eater. Theoretically DLSS can work as a denoiser for high rpp (aka very clean) signals. REBLUR works flawlessly with DLSS. To be honest, I have a version of this repo with integrated DLSS. Since DLSS is a major part of raytracing, of course, I spent a lot of time making REBLUR more stable when DLSS is active.

Unfortunately, DLSS repo requires a separate approval, so I can't post NRD sample with DLSS here. It's being discussed, we do hope that we find a solution in the future.

**Comment by BattleAxeVR** [comment]
Thank you, that it works is great news and so I really hope DLSS is opened up to engines other than Unreal at some point.

**Comment by BattleAxeVR** [comment]
Now that DLSS is opened up to public use, will it be integrated here? That would save some time for me. 

The latest sync appears to have nuked the sample, too.
