### ISSUE TITLE
Licensing Issue?

### ISSUE THREAD

**Issue by wangyuehi** [NVIDIA-RTX/NRD#31]
Hi, 
Not sure if this is the place to ask, but seems it's not mentioned on the wiki page:
is there any suggestion on getting the proper licensing for use in production in an game engine? 

Thanks

**Comment by BattleAxeVR** [comment]
I would also like to know this.

**Comment by tiont** [comment]
Hi @wangyuehi and @BattleAxeVR . The NRD SDK license is included in the repo in the "LICENSE.txt" file at the root. In general, the terms include freedom to incorporate the SDK and modify it for shipping in a production title. The key point is that you are not allowed to redistribute the SDK source code as is, but can only include it in binary or object form (see section 1c). We also require that you add a line in any derivative work: "This software contains source code provided by NVIDIA Corporation." (see section 2b). 

Otherwise, no restrictions on commercial use for this SDK. Please take a look at the full license file and let us know if you have any further questions. 

Thank you,
Tion Thomas

**Comment by BattleAxeVR** [comment]
Thanks a lot for the clarification.

**Comment by stkrake** [comment]
What about point 6.1 c) "...you must attribute the use of the applicable SDK and include the NVIDIA Marks on the credit screen..." (which leads to 6.2 c) "...submit a sample of each proposed use of NVIDIA's Marks...")?

**Comment by tiont** [comment]
@stkrake yes, if you plan to release a product derived from the SDK for commercial use, then you must add an Nvidia attribution and NVIDIA marks on the credit screen as stated.

**Comment by stkrake** [comment]
> @stkrake yes, if you plan to release a product derived from the SDK for commercial use, then you must add an Nvidia attribution and NVIDIA marks on the credit screen as stated.

Thanks. That's how I understood it, too. What would be the right contact for all things around NVIDIA marks, usage guidelines and approval? nvidia-rtx-license-questions@nvidia.com?

**Comment by tiont** [comment]
@stkrake please refer to the Nvidia logos and brand guidelines here: [https://www.nvidia.com/en-us/about-nvidia/legal-info/logo-brand-usage](https://www.nvidia.com/en-us/about-nvidia/legal-info/logo-brand-usage)

Note that there is a "request approval" button that will connect you with the appropriate resources at Nvidia to approve your Nvidia marks submission.

**Comment by stkrake** [comment]
> @stkrake please refer to the Nvidia logos and brand guidelines here: https://www.nvidia.com/en-us/about-nvidia/legal-info/logo-brand-usage

Many thanks! I already searched desperately for something like that :-)

**Comment by tiont** [comment]
Your welcome. We look forward to seeing your work with NRD!

**Comment by stkrake** [comment]
Sorry to to come back to this again. But the "request approval" button is gone! Are there any other ways to contact the appropriate resources at Nvidia?

**Comment by tiont** [comment]
@stkrake Thank you for making us aware of that. Not sure why the button was removed but I am inquiring with our internal teams. I hope to you get back to you soon with appropriate next steps to get your Marks approved.
