### ISSUE TITLE
add support for Linux

### ISSUE THREAD

**Issue by earjuice** [NVIDIA-RTX/NRD#8]
Be really nice(detrimental) to run this in Linux Ubuntu/Fedora..
but I guess the Windows SDK would prevent one from translating the batch files to shell..

**Comment by natevm** [comment]
+1 

I would like to integrate this into a cross platform OptiX app at some point. I have some end users that want to denoise some sim2real ray traced images, where rendering is done semi-interactively on a Linux render farm. (Right now they’re just using an OpenGL rasterizer)

I looked into this before, and it seems doable from an outsiders perspective, since it looks like a lot of the backend is written in Vulkan. But I’m not sure how difficult it would be to adjust the build system.

**Comment by dzhdanNV** [comment]
NRD itself should be cross-platform (but there can be various compilation difficulties). The framework is more complex:
- NRI is OK, D3D12 backend can be disabled for Linux
- SampleBase requires significant code massaging and potential migration to a light-weight SDL-like library

There are some folks who started porting, but everyday devtech duties block them...

**Comment by earjuice** [comment]
> NRD itself should be cross-platform (but there can be various compilation difficulties). The framework is more complex:
> 
>     * NRI is OK, D3D12 backend can be disabled for Linux
> 
>     * SampleBase requires significant code massaging and potential migration to a light-weight SDL-like library
> 
> 
> There are some folks who started porting, but everyday devtech duties block them...

That's great! ... would be running this in Vulkan on Linux.  looking at it again.. you're right. It looks like most of the gunk was to set up VS in windows and I've totally translated Nvidia Graphics Samples into other frameworks before such as Cinder for proof of concept and better understanding. This shouldn't be too hard to get working then and would be a similar feat.  Hopefully the "compilation difficulties" aren't too difficult either.  Thanks for confirming it's cross-platform-ability despite the windows visual studio samples setup. Makes sense now.  I'll see what I can do. Cheers.
